# Generated by Django 5.0 on 2023-12-13 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.DecimalField(decimal_places=0, max_digits=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
