# Generated by Django 5.0 on 2023-12-15 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_id'),
        # ('leaderboard', '0003_delete_friendship'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
