# Generated by Django 5.0 on 2023-12-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_losses_user_total_matches_user_wins'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, default='default_profile_picture.PNG', null=True, upload_to='authentication/images/'),
        ),
    ]
