# Generated by Django 5.0 on 2023-12-20 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='picture',
            new_name='profile_picture',
        ),
    ]
