# Generated by Django 5.0 on 2024-03-04 10:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_userchannelname'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userchannelname',
            unique_together={('user', 'channel_name')},
        ),
    ]
