# Generated by Django 5.0 on 2023-12-15 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0002_alter_friendship_unique_together_friendship_accepted_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friendship',
        ),
    ]
