# Generated by Django 5.0 on 2024-04-19 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamestats',
            name='game_history',
        ),
        migrations.RemoveField(
            model_name='gamestats',
            name='user',
        ),
        migrations.DeleteModel(
            name='GameHistory',
        ),
        migrations.DeleteModel(
            name='GameStats',
        ),
    ]
