# Generated by Django 5.0 on 2024-04-28 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_remove_gamestats_game_history_remove_gamestats_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserChannelName',
        ),
    ]
