# Generated by Django 5.0 on 2023-12-29 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0006_rename_user_id_appuser_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='friends',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='received_friend_requests',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='sent_friend_requests',
        ),
        migrations.DeleteModel(
            name='FriendRequest',
        ),
    ]
