# Generated by Django 5.0 on 2024-01-22 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0012_blacklistedtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='TwoFA',
            field=models.BooleanField(default=False),
        ),
    ]
