# Generated by Django 5.0 on 2024-01-28 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0013_appuser_twofa'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='AboutMe',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='intra_level',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='appuser',
            name='match_history',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='appuser',
            name='school',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='win_rate',
            field=models.FloatField(default=0),
        ),
    ]
