# Generated by Django 5.0 on 2024-02-14 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0015_appuser_ft_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='ft_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
