# Generated by Django 5.0 on 2024-03-14 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friendship_api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follower',
        ),
    ]
