name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Install Dependencies
        working-directory: frontend
        run: npm install

      - name: Run Tests
        working-directory: frontend
        run: npm test

      - name: Build Frontend
        working-directory: frontend
        run: npm run build

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to GitHub Pages
        run: |
          npm install -g github-pages-deploy-action
          gh-pages-deploy --token ${{ secrets.ACCESS_TOKEN }} --branch gh-pages --dir frontend/build
        working-directory: /
